language: go
go:
  - "1.10"
sudo: false
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
  - export PATH=$PATH:$PWD/src/github.com/ioeXNetwork/
  - glide install
branches:
  only:
  - master
  - dev
